floor_markers:
  4:
    floor_number: 4
    map_yaml: "/home/ubuntu/fp_ws/final_project/flooring/maps/4f.yaml"
    initial_pose:
      x: 0.8
      y: 0.3
      yaw: 1.57
  5:
    floor_number: 5
    map_yaml: "/home/ubuntu/fp_ws/final_project/flooring/maps/5f.yaml"
    initial_pose:
      x: 0.8
      y: 0.3
      yaw: 1.57
    
      
   
