floors:
  4:
    map: "maps/floor4.yaml"
    dock:           {x:  3.748, y: -18.219, yaw: 0.0} # yaw 는 추후 조정
    elevator_entering: {x: -0.022, y: 0.090, yaw: 0.0}
    elevator_exiting: {x: -0.022, y: 0.090, yaw: 0.0} # exiting 의 yaw 는 -entering yaw
    rooms:
      "401":        {x: -0.535, y: -10.839, yaw: 0.0}
      "402":        {x:  2.678, y: -10.399, yaw: 0.0}
  5:
    map: "maps/floor5.yaml"
    dock:           {x: -0.226, y: -0.154, yaw: 0.0}
    elevator_entering: {x: 15.771, y: 2.634, yaw: 0.0}
    elevator_exiting: {x: 15.771, y: 2.634, yaw: 0.0}
    rooms:
      "501":        {x: 6.318, y: 1.524, yaw: 0.0}